export const MAKE_VISIBLE = 'MAKE_VISIBLE';

export const SET_CURRENT_WIDGET = 'SET_CURRENT_WIDGET';
export const REMOVE_EDITOR = 'REMOVE_EDITOR';
export const DUPLICATE_EDITOR = 'DUPLICATE_EDITOR';
export const SET_EDITOR_POSITION = 'SET_EDITOR_POSITION';
export const SET_EDITOR_SIZE = 'SET_EDITOR_SIZE';
export const UPDATE_FILE = 'UPDATE_FILE';

export const ADD_CODE_EDITOR = 'ADD_CODE_EDITOR';
export const PLAY_CODE = 'PLAY_CODE';
export const STOP_CODE = 'STOP_CODE';
export const SET_INNER_WIDTH = 'SET_INNER_WIDTH';
export const SET_INNER_HEIGHT = 'SET_INNER_HEIGHT';
export const START_CODE_REFRESH = 'START_CODE_REFRESH';
export const STOP_CODE_REFRESH = 'STOP_CODE_REFRESH';
export const RECIEVE_MESSAGE = 'RECIEVE_MESSAGE';
export const SET_EDITOR_MODE = 'SET_EDITOR_MODE';
export const SET_CURRENT_FILE = 'SET_CURRENT_FILE';
export const CLEAR_CONSOLE_OUTPUT = 'CLEAR_CONSOLE_OUTPUT';
export const UPDATE_CONSOLE_OUTPUT = 'UPDATE_CONSOLE_OUTPUT';
export const ADD_TEXT_EDITOR = 'ADD_TEXT_EDITOR';
export const UPDATE_TEXT_CHANGE = 'UPDATE_TEXT_CHANGE';
export const UPDATE_TEXT_BACK_COLOR = 'UPDATE_TEXT_BACK_COLOR';
export const RESIZE_TEXT_EDITOR = 'RESIZE_TEXT_EDITOR';
export const UPDATE_TEXT_HEIGHT = 'UPDATE_TEXT_HEIGHT';
export const ADD_IFRAME = 'ADD_IFRAME';
export const SET_IFRAME_URL = 'SET_IFRAME_URL';
export const ADD_QUESTION_EDITOR = 'ADD_QUESTION_EDITOR';
export const SET_QUESTION_INNER_HEIGHT = 'SET_QUESTION_INNER_HEIGHT';
export const UPDATE_QUESTION_CHANGE = 'UPDATE_QUESTION_CHANGE';
export const UPDATE_ANSWER_CHANGE = 'UPDATE_ANSWER_CHANGE';
export const ADD_IMAGE = 'ADD_IMAGE';
export const SET_IMAGE_URL = 'SET_IMAGE_URL';

export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';
export const SUBMIT_PAGE = 'SUBMIT_PAGE';
export const CREATE_PAGE = 'CREATE_PAGE';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const SET_ALL_PAGES = 'SET_ALL_PAGES';
export const DELETE_PAGE = 'DELETE_PAGE';
export const SET_UNSAVED_CHANGES = 'SET_UNSAVED_CHANGES';

export const SET_DB_PAGE = 'SET_DB_PAGE';
export const SET_PAGE_ID = 'SET_PAGE_ID';
export const SET_PAGE_LAYOUT = 'SET_PAGE_LAYOUT';
export const SET_DB_EDITORS = 'SET_DB_EDITORS';
export const SET_DB_TEXT_EDITORS = 'SET_DB_TEXT_EDITORS';
export const TOGGLE_PREVIEW_MODE = 'TOGGLE_PREVIEW_MODE';
export const SET_PREVIEW_MODE = 'SET_PREVIEW_MODE';

export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';
export const UPDATE_USER_NAME = 'UPDATE_USER_NAME';
export const SIGN_USER_UP = 'SIGN_USER_UP';
export const LOGIN_USER = 'LOGIN_USER';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_TYPE = 'SET_USER_TYPE';
export const MATCH_USER_NAME = 'MATCH_USER_NAME';
export const SET_EDIT_ACCESS = 'SET_EDIT_ACCESS';

export const VIEW_EXAMPLES_MODAL = 'VIEW_EXAMPLES_MODAL';
export const CLOSE_EXAMPLES_MODAL = 'CLOSE_EXAMPLES_MODAL';
export const VIEW_PAGES_MODAL = 'VIEW_PAGES_MODAL';
export const CLOSE_PAGES_MODAL = 'CLOSE_PAGES_MODAL';
export const VIEW_SHARE_MODAL = 'VIEW_SHARE_MODAL';
export const CLOSE_SHARE_MODAL = 'CLOSE_SHARE_MODAL';
export const VIEW_LOGIN_MODAL = 'VIEW_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const VIEW_SIGN_UP_MODAL = 'VIEW_SIGN_UP_MODAL';
export const CLOSE_SIGN_UP_MODAL = 'CLOSE_SIGN_UP_MODAL';
export const VIEW_FORGOT_MODAL = 'VIEW_FORGOT_MODAL';
export const CLOSE_FORGOT_MODAL = 'CLOSE_FORGOT_MODAL';
export const VIEW_RESET_MODAL = 'VIEW_RESET_MODAL';
export const CLOSE_RESET_MODAL = 'CLOSE_RESET_MODAL';
export const VIEW_CONFIRM_USER_MODAL = 'VIEW_CONFIRM_USER_MODAL';
export const CLOSE_CONFIRM_USER_MODAL = 'CLOSE_CONFIRM_USER_MODAL';

export const TOGGLE_FILE_DROPDOWN = 'TOGGLE_FILE_DROPDOWN';
export const TOGGLE_ACCOUNT_DROPDOWN = 'TOGGLE_ACCOUNT_DROPDOWN';

export const SET_PROFILE_NAME = 'SET_PROFILE_NAME';
export const SET_PROFILE_PEBLS = 'SET_PROFILE_PEBLS';
export const SET_PROFILE_FOLDERS = 'SET_PROFILE_FOLDERS';
export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE';
export const SET_PROFILE_DESC = 'SET_PROFILE_DESC';
export const SET_IS_OWNER = 'SET_IS_OWNER';

export const CREATE_FOLDER = 'CREATE_FOLDER';
export const DELETE_FOLDER = 'DELETE_FOLDER';
export const RENAME_FOLDER = 'RENAME_FOLDER';
export const UPDATE_FOLDER = 'UPDATE_FOLDER';
export const MOVE_PAGE_TO_TOP_LEVEL = 'MOVE_PAGE_TO_TOP_LEVEL';
export const MOVE_PAGE_TO_FOLDER = 'MOVE_PAGE_TO_FOLDER';
export const MOVE_FOLDER_TO_TOP_LEVEL = 'MOVE_FOLDER_TO_TOP_LEVEL';
export const MOVE_FOLDER_TO_FOLDER = 'MOVE_FOLDER_TO_FOLDER';
export const VIEW_FOLDER = 'VIEW_FOLDER';
export const VIEW_PAGE = 'VIEW_PAGE';
export const CLEAR_SELECTED_FOLDERS = 'CLEAR_SELECTED_FOLDERS';
