export const MAKE_VISIBLE = 'MAKE_VISIBLE';

export const SET_CURRENT_EDITOR = 'SET_CURRENT_EDITOR';
export const REMOVE_EDITOR = 'REMOVE_EDITOR';
export const SET_EDITOR_POSITION = 'SET_EDITOR_POSITION';
export const SET_EDITOR_SIZE = 'SET_EDITOR_SIZE';
export const UPDATE_FILE = 'UPDATE_FILE';

export const ADD_CODE_EDITOR = 'ADD_CODE_EDITOR';
export const PLAY_CODE = 'PLAY_CODE';
export const STOP_CODE = 'STOP_CODE';
export const RECIEVE_MESSAGE = 'RECIEVE_MESSAGE';
export const SET_EDITOR_MODE = 'SET_EDITOR_MODE';
export const SET_CURRENT_FILE = 'SET_CURRENT_FILE';
export const UPDATE_CONSOLE_OUTPUT = 'UPDATE_CONSOLE_OUTPUT';
export const ADD_TEXT_EDITOR = 'ADD_TEXT_EDITOR';
export const UPDATE_TEXT_CHANGE = 'UPDATE_TEXT_CHANGE';
export const ADD_IFRAME = 'ADD_IFRAME';
export const SET_IFRAME_URL = 'SET_IFRAME_URL';

export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';
export const SUBMIT_PAGE = 'SUBMIT_PAGE';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const SET_ALL_PAGES = 'SET_ALL_PAGES';
export const DELETE_PAGE = 'DELETE_PAGE';
export const SET_UNSAVED_CHANGES = 'SET_UNSAVED_CHANGES';

export const SET_DB_PAGE = 'SET_DB_PAGE';
export const SET_PAGE_ID = 'SET_PAGE_ID';
export const SET_DB_EDITORS = 'SET_DB_EDITORS';
export const SET_DB_TEXT_EDITORS = 'SET_DB_TEXT_EDITORS';
export const TOGGLE_PREVIEW_MODE = 'TOGGLE_PREVIEW_MODE';

export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';
export const UPDATE_USER_NAME = 'UPDATE_USER_NAME';
export const SIGN_USER_UP = 'SIGN_USER_UP';
export const LOGIN_USER = 'LOGIN_USER';
export const SET_USER_NAME = 'SET_USER_NAME';
export const MATCH_USER_NAME = 'MATCH_USER_NAME';
export const SET_EDIT_ACCESS = 'SET_EDIT_ACCESS';

export const VIEW_PAGES_MODAL = 'VIEW_PAGES_MODAL';
export const CLOSE_PAGES_MODAL = 'CLOSE_PAGES_MODAL';
export const VIEW_LOGIN_MODAL = 'VIEW_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const VIEW_SIGN_UP_MODAL = 'VIEW_SIGN_UP_MODAL';
export const CLOSE_SIGN_UP_MODAL = 'CLOSE_SIGN_UP_MODAL';
export const TOGGLE_FILE_DROPDOWN = 'TOGGLE_FILE_DROPDOWN';
