export const MAKE_VISIBLE = 'MAKE_VISIBLE';

export const ADD_EDITOR = 'ADD_EDITOR';
export const PLAY_CODE = 'PLAY_CODE';
export const RECIEVE_MESSAGE = 'RECIEVE_MESSAGE';
export const SET_CURRENT_EDITOR = 'SET_CURRENT_EDITOR';
export const SET_EDITOR_MODE = 'SET_EDITOR_MODE';
export const STOP_CODE = 'STOP_CODE';
export const UPDATE_CODE = 'UPDATE_CODE';
export const UPDATE_CONSOLE_OUTPUT = 'UPDATE_CONSOLE_OUTPUT';
