export const MAKE_VISIBLE = 'MAKE_VISIBLE';

export const WP_PLAY_CODE = 'WP_PLAY_CODE';
export const WP_STOP_CODE = 'WP_STOP_CODE';
export const WP_START_CODE_REFRESH = 'WP_START_CODE_REFRESH';
export const WP_STOP_CODE_REFRESH = 'WP_STOP_CODE_REFRESH';
export const WP_ADD_MEDIA_FILE = 'WP_ADD_MEDIA_FILE';
export const WP_UPDATE_CONSOLE_OUTPUT = 'WP_UPDATE_CONSOLE_OUTPUT';
export const WP_CLEAR_CONSOLE_OUTPUT = 'WP_CLEAR_CONSOLE_OUTPUT';
export const WP_UPDATE_FILE = 'WP_UPDATE_FILE';
export const WP_SET_CURRENT_FILE = 'WP_SET_CURRENT_FILE';
export const WP_SET_INNER_WIDTH = 'WP_SET_INNER_WIDTH';
export const WP_SET_INNER_HEIGHT = 'WP_SET_INNER_HEIGHT';
export const LOAD_WORKSPACE = 'LOAD_WORKSPACE';
export const TOGGLE_WORKSPACE = 'TOGGLE_WORKSPACE';
export const WP_SET_EDITOR_MODE = 'WP_SET_EDITOR_MODE';
export const OPEN_SHARE_WORKSPACE = 'OPEN_SHARE_WORKSPACE';
export const CLOSE_SHARE_WORKSPACE = 'CLOSE_SHARE_WORKSPACE';

export const SET_CURRENT_WIDGET = 'SET_CURRENT_WIDGET';
export const REMOVE_EDITOR = 'REMOVE_EDITOR';
export const DUPLICATE_EDITOR = 'DUPLICATE_EDITOR';
export const UPDATE_FILE = 'UPDATE_FILE';

export const ADD_CODE_EDITOR = 'ADD_CODE_EDITOR';
export const ADD_MEDIA_FILE = 'ADD_MEDIA_FILE';
export const PLAY_CODE = 'PLAY_CODE';
export const STOP_CODE = 'STOP_CODE';
export const SET_INNER_WIDTH = 'SET_INNER_WIDTH';
export const SET_INNER_HEIGHT = 'SET_INNER_HEIGHT';
export const START_CODE_REFRESH = 'START_CODE_REFRESH';
export const STOP_CODE_REFRESH = 'STOP_CODE_REFRESH';
export const RECIEVE_MESSAGE = 'RECIEVE_MESSAGE';
export const SET_CURRENT_FILE = 'SET_CURRENT_FILE';
export const VIEW_EDITOR_PREVIEW = 'VIEW_EDITOR_PREVIEW';
export const CLEAR_CONSOLE_OUTPUT = 'CLEAR_CONSOLE_OUTPUT';
export const UPDATE_CONSOLE_OUTPUT = 'UPDATE_CONSOLE_OUTPUT';
export const ADD_EDITOR = 'ADD_EDITOR';
export const SET_EDITOR_VIEW = 'SET_EDITOR_VIEW';

export const ADD_TEXT_EDITOR = 'ADD_TEXT_EDITOR';
export const UPDATE_TEXT_CHANGE = 'UPDATE_TEXT_CHANGE';
export const UPDATE_TEXT_BACK_COLOR = 'UPDATE_TEXT_BACK_COLOR';
export const RESIZE_TEXT_EDITOR = 'RESIZE_TEXT_EDITOR';
export const UPDATE_TEXT_HEIGHT = 'UPDATE_TEXT_HEIGHT';

export const ADD_IFRAME = 'ADD_IFRAME';
export const SET_IFRAME_URL = 'SET_IFRAME_URL';
export const ADD_VIDEO = 'ADD_VIDEO';
export const SET_VIDEO_URL = 'SET_VIDEO_URL';
export const ADD_QUESTION_EDITOR = 'ADD_QUESTION_EDITOR';
export const SET_QUESTION_INNER_HEIGHT = 'SET_QUESTION_INNER_HEIGHT';
export const UPDATE_QUESTION_CHANGE = 'UPDATE_QUESTION_CHANGE';
export const UPDATE_ANSWER_CHANGE = 'UPDATE_ANSWER_CHANGE';

export const ADD_IMAGE = 'ADD_IMAGE';
export const SET_IMAGE_URL = 'SET_IMAGE_URL';
export const SET_IMAGE_CROP = 'SET_IMAGE_CROP';
export const RESET_IMAGE_CROP = 'RESET_IMAGE_CROP';

export const SET_PAGE_AUTHOR = 'SET_PAGE_AUTHOR';
export const SET_PARENT_PAGE_AUTHOR = 'SET_PARENT_PAGE_AUTHOR';
export const ADD_PAGE_TAG = 'ADD_PAGE_TAG';
export const DELETE_PAGE_TAG = 'DELETE_PAGE_TAG';
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';
export const SET_PAGE_HEADING = 'SET_PAGE_HEADING';
export const SUBMIT_PAGE = 'SUBMIT_PAGE';
export const CREATE_PAGE = 'CREATE_PAGE';
export const DUPLICATE_PAGE = 'DUPLICATE_PAGE';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const SET_ALL_PAGES = 'SET_ALL_PAGES';
export const DELETE_PAGE = 'DELETE_PAGE';
export const SET_UNSAVED_CHANGES = 'SET_UNSAVED_CHANGES';
export const AUTO_SAVE_UNSAVED_CHANGES = 'AUTO_SAVE_UNSAVED_CHANGES';

export const SET_DB_PAGE = 'SET_DB_PAGE';
export const SET_PAGE_ID = 'SET_PAGE_ID';
export const SET_PAGE_LAYOUT = 'SET_PAGE_LAYOUT';
export const SET_DB_EDITORS = 'SET_DB_EDITORS';
export const SET_DB_TEXT_EDITORS = 'SET_DB_TEXT_EDITORS';
export const TOGGLE_PREVIEW_MODE = 'TOGGLE_PREVIEW_MODE';
export const SET_PREVIEW_MODE = 'SET_PREVIEW_MODE';

export const SIGN_USER_UP = 'SIGN_USER_UP';
export const LOGIN_USER = 'LOGIN_USER';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_TYPE = 'SET_USER_TYPE';
export const SET_USER_BROWSING_PEBL = 'SET_USER_BROWSING_PEBL';
export const MATCH_USER_NAME = 'MATCH_USER_NAME';
export const SET_EDIT_ACCESS = 'SET_EDIT_ACCESS';
export const SET_GUARDIAN_CONSENT = 'SET_GUARDIAN_CONSENT';

export const VIEW_EXAMPLES_MODAL = 'VIEW_EXAMPLES_MODAL';
export const CLOSE_EXAMPLES_MODAL = 'CLOSE_EXAMPLES_MODAL';
export const VIEW_FORK_PROMPT = 'VIEW_FORK_PROMPT';
export const CLOSE_FORK_PROMPT = 'CLOSE_FORK_PROMPT';
export const VIEW_PAGES_MODAL = 'VIEW_PAGES_MODAL';
export const CLOSE_PAGES_MODAL = 'CLOSE_PAGES_MODAL';
export const VIEW_SHARE_MODAL = 'VIEW_SHARE_MODAL';
export const CLOSE_SHARE_MODAL = 'CLOSE_SHARE_MODAL';
export const VIEW_LOGIN_MODAL = 'VIEW_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const VIEW_SIGN_UP_MODAL = 'VIEW_SIGN_UP_MODAL';
export const CLOSE_SIGN_UP_MODAL = 'CLOSE_SIGN_UP_MODAL';
export const VIEW_FORGOT_MODAL = 'VIEW_FORGOT_MODAL';
export const CLOSE_FORGOT_MODAL = 'CLOSE_FORGOT_MODAL';
export const VIEW_RESET_MODAL = 'VIEW_RESET_MODAL';
export const CLOSE_RESET_MODAL = 'CLOSE_RESET_MODAL';
export const VIEW_CONFIRM_USER_MODAL = 'VIEW_CONFIRM_USER_MODAL';
export const CLOSE_CONFIRM_USER_MODAL = 'CLOSE_CONFIRM_USER_MODAL';
export const VIEW_WELCOME_MODAL = 'VIEW_WELCOME_MODAL';
export const CLOSE_WELCOME_MODAL = 'CLOSE_WELCOME_MODAL';
export const TOGGLE_PREFERENCES_PANEL = 'TOGGLE_PREFERENCES_PANEL';

export const TOGGLE_HELP_DROPDOWN = 'TOGGLE_HELP_DROPDOWN';
export const TOGGLE_FILE_DROPDOWN = 'TOGGLE_FILE_DROPDOWN';
export const TOGGLE_ACCOUNT_DROPDOWN = 'TOGGLE_ACCOUNT_DROPDOWN';

export const SET_USER = 'SET_USER';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_PROFILE_PEBLS = 'SET_PROFILE_PEBLS';
export const SET_PROFILE_FOLDERS = 'SET_PROFILE_FOLDERS';
export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE';
export const SET_PROFILE_BLURB = 'SET_PROFILE_BLURB';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_IS_OWNER = 'SET_IS_OWNER';

export const CREATE_FOLDER = 'CREATE_FOLDER';
export const DELETE_FOLDER = 'DELETE_FOLDER';
export const RENAME_FOLDER = 'RENAME_FOLDER';
export const UPDATE_FOLDER = 'UPDATE_FOLDER';
export const MOVE_PAGE_TO_TOP_LEVEL = 'MOVE_PAGE_TO_TOP_LEVEL';
export const MOVE_PAGE_TO_FOLDER = 'MOVE_PAGE_TO_FOLDER';
export const MOVE_FOLDER_TO_TOP_LEVEL = 'MOVE_FOLDER_TO_TOP_LEVEL';
export const MOVE_FOLDER_TO_FOLDER = 'MOVE_FOLDER_TO_FOLDER';
export const VIEW_FOLDER = 'VIEW_FOLDER';
export const VIEW_PAGE = 'VIEW_PAGE';
export const JUMP_TO_FOLDER = 'JUMP_TO_FOLDER';
export const CLEAR_SELECTED_FOLDERS = 'CLEAR_SELECTED_FOLDERS';

export const UPDATE_EDITOR_THEME = 'UPDATE_EDITOR_THEME';
export const UPDATE_EDITOR_FONT_SIZE = 'UPDATE_EDITOR_FONT_SIZE';
export const SET_USER_PREFERENCES = 'SET_USER_PREFERENCES';

export const CLOSE_NAVIGATION = 'CLOSE_N`AVIGATION';
export const CREATE_NAVIGATION_CONTENT = 'CREATE_NAVIGATION_CONTENT';
export const OPEN_NAVIGATION = 'OPEN_NAVIGATION';
export const SET_Y_NAVIGATION = 'SET_Y_NAVIGATION';
